server:
  port: 9999
spring:
  application:
    name: gateway
  redis:
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      default-filters:
        - StripPrefix= 1
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 1
            key-resolver: "#{@ipKeyResolver}"
      routes:
        - id: service-verificationcode-numberCode # 路由标示，必须唯一
          uri: lb://service-verificationcode # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/serviceVerificationcode/**
        - id: api-passenger-verification-code
          uri: lb://api-passenger
          predicates:
            - Path=/passenger/**