server:
  port: 9999
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: service-verificationcode # 路由标示，必须唯一
          uri: lb://service-verificationcode # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/test/** # 路径断言，判断路径是否是以/user开头，如果是则符合