server:
  port: 8086

spring:
  datasource:
    name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/service-driver-user?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 20000113a@
  application:
    name: service-driver-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
