server:
  port: 8085

spring:
  cloud:
    nacos:
      discovery:
        server-addr:127.0.0.1:8848
  application:
    name: service-map
  datasource:
    name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/service-map?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 20000113a@

amap:
  key: cbb3992f13d366b3d3040d76ff30a63d
  sid : 840072
